name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  APPLITOOLS_SERVER_URL: "https://eyesapi.applitools.com"
  APPLITOOLS_BATCH_ID: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - if: ${{ github.event.pull_request }}
        run: echo "APPLITOOLS_BATCH_ID=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci
      - run: npm install chromedriver --detect_chromedriver_version

      - run: npm run test:ci

      - name: Update Applitools batch status
        uses: wei/curl@v1.1.1
        with:
          args: -d \"\" -X POST "${{ env.APPLITOOLS_SERVER_URL }}/api/Externals/github/servers/github.com/commit/${{ env.APPLITOOLS_BATCH_ID }}/complete?apiKey=${{ env.APPLITOOLS_API_KEY }}"
